/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Simple_Banking_System;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;
import java.io.File;


public class AppTest {
    @Test public void applicationDatabaseCheck() {
        String databaseFileName = System.getProperty("user.dir") + "/card.s3db";
        File file = new File(databaseFileName);
        assertTrue(file.exists());
    }
}
